In [77]:
pip install datasets

Requirement already satisfied: datasets in .\.venv\Lib\site-packages (4.8.5)
Requirement already satisfied: filelock in .\.venv\Lib\site-packages (from datasets) (3.29.0)
Requirement already satisfied: numpy>=1.17 in .\.venv\Lib\site-packages (from datasets) (2.4.4)
Requirement already satisfied: pyarrow>=21.0.0 in .\.venv\Lib\site-packages (from datasets) (24.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in .\.venv\Lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in .\.venv\Lib\site-packages (from datasets) (3.0.2)
Requirement already satisfied: requests>=2.32.2 in .\.venv\Lib\site-packages (from datasets) (2.33.1)
Requirement already satisfied: httpx<1.0.0 in .\.venv\Lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in .\.venv\Lib\site-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in .\.venv\Lib\site-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess<0.70.20 in .\.venv\Lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in .\.venv\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2026.2.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in .\.venv\Lib\site-packages (from datasets) (1.14.0)
Requirement already satisfied: packaging in .\.venv\Lib\site-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in .\.venv\Lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in .\.venv\Lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in .\.venv\Lib\site-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in .\.venv\Lib\site-packages (from httpx<1.0.0->datasets) (2026.4.22)
Requirement already satisfied: httpcore==1.* in .\.venv\Lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in .\.venv\Lib\site-packages (from httpx<1.0.0->datasets) (3.13)
Requirement already satisfied: h11>=0.16 in .\.venv\Lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in .\.venv\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.0)
Requirement already satisfied: typer>=0.20.0 in .\.venv\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in .\.venv\Lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.15.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in .\.venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in .\.venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in .\.venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in .\.venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in .\.venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in .\.venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in .\.venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\.venv\Lib\site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in .\.venv\Lib\site-packages (from requests>=2.32.2->datasets) (2.7.0)
Requirement already satisfied: colorama in .\.venv\Lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: click>=8.2.1 in .\.venv\Lib\site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in .\.venv\Lib\site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in .\.venv\Lib\site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in .\.venv\Lib\site-packages (from typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\.venv\Lib\site-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\.venv\Lib\site-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in .\.venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [78]:
import datasets
from transformers import pipeline
from transformers.pipelines.pt_utils import KeyDataset
from tqdm.auto import tqdm

In [79]:
import pandas as pd
hdfc = pd.read_csv("HDFC_news_21.csv")
hdfc.tail()

,headline,date,link
2509,"HDFC Bank Limited, Q3 2020 Earnings Call, Jan ...",05:00:00 18/01/2020 pm IST,/quote/stock/HDFC-BANK-LIMITED-105516154/news/...
2510,Hdfc Bank Limited Reports Earnings Results for...,04:01:00 18/01/2020 pm IST,/quote/stock/HDFC-BANK-LIMITED-105516154/news/...
2511,Housing Development Finance Corporation Bank o...,04:30:00 14/01/2020 am IST,/quote/stock/HOUSING-DEVELOPMENT-FINAN-2070303...
2512,"CSL Finance Limited, Q2 2020 Earnings Call, Ja...",04:00:00 07/01/2020 pm IST,/quote/stock/CSL-FINANCE-LIMITED-44377569/news...
2513,"Ketan Harilal Mehta, Managing Director of Amba...",04:30:00 19/12/2019 am IST,/quote/stock/AMBA-ENTERPRISES-LIMITED-46731303...

In [80]:
hdfc_rev = hdfc.iloc[::-1].reset_index(drop=True)

In [105]:
hdfc_rev.tail()

,headline,date,link
2509,Asian Equities Traded in the US as American De...,08:03:09 25/04/2025 pm IST,/quote/stock/UXIN-LIMITED-44403618/news/Asian-...
2510,HDFC Bank : Parivartan inaugurates its first ‘...,02:24:07 28/04/2025 pm IST,/quote/stock/HDFC-BANK-LIMITED-105516154/news/...
2511,HDFC Bank : Earnings Call Transcript Q4FY25,04:32:07 28/04/2025 pm IST,/quote/stock/HDFC-BANK-LIMITED-105516154/news/...
2512,Asian Equities Traded in the US as American De...,08:10:13 28/04/2025 pm IST,/quote/stock/SIFY-TECHNOLOGIES-LIMITED-10829/n...
2513,Asian Equities Traded in the US as American De...,08:07:25 29/04/2025 pm IST,/quote/stock/VNET-GROUP-INC-7855123/news/Asian...

In [82]:
data = hdfc_rev

In [83]:
from transformers import pipeline

pipe = pipeline("text-classification", model="ProsusAI/finbert", top_k = None)
lables = ["positive", "negative", 'neutral']

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [84]:
results = pipe(data["headline"].tolist())

In [98]:
parsed_rows = []
for rows in results :
    clean_dict = {'positive': 0.0, 'negative': 0.0, 'neutral': 0.0}

    for pred in rows:
        label = pred['label']
        score = pred['score']
        clean_dict[label] = score
        parsed_rows.append(clean_dict)

output = pd.DataFrame(parsed_rows)

In [102]:
output['Date'] = hdfc['date']

In [103]:
output = output.iloc[::3]
output.reset_index(drop=True)

     positive  negative   neutral                        Date
0    0.135713  0.009076  0.855212  08:07:25 29/04/2025 pm IST
1    0.131032  0.012874  0.856094  10:44:00 21/04/2025 am IST
2    0.065565  0.018418  0.916016  02:11:13 15/04/2025 pm IST
3    0.020502  0.040706  0.938793  07:39:15 28/03/2025 pm IST
4    0.027194  0.039978  0.932828  04:30:00 09/03/2025 am IST
..        ...       ...       ...                         ...
275  0.032411  0.033498  0.934091                         NaN
276  0.025577  0.030053  0.944370                         NaN
277  0.941549  0.026723  0.031728                         NaN
278  0.937542  0.025897  0.036561                         NaN
279  0.038934  0.050491  0.910575                         NaN

[280 rows x 4 columns]

In [92]:
output.to_csv('sentiment.csv',index = False )